version: "3"

services:
    mizun_bot:
        restart: unless-stopped
        network_mode: "host"
        build: .
        volumes:
        - ./app:/app
        environment:
        # eth0, lo, etc.
        - NIC_NAME=ens192

        # Create a bot in @BotFather and place the bot token here
        - BOT_TOKEN=1900720213:AAF4ooKt-fOyL9BvtsDRGroHe9qeP-Mzx4A
        
        # Use @getidsbot bot in Telegram to get your id
        - ADMIN_UID=95374546