version: "3"

services:
    mizun_bot:
        restart: unless-stopped
        network_mode: "host"
        build: .
        volumes:
        - ./app:/app
        environment:
        - BOT_TOKEN: "xxxxxxxxxxxx"
        - ADMIN_UID: "xxxxx"