version: "3"

services:
    mizun_bot:
        restart: unless-stopped
        network_mode: "host"
        build: .
        volumes:
        - ./app:/app
        environment:
        - BOT_TOKEN= "1884354297:AAFs6shA-k397Wonu-3g_rlHG5ZjJ6OJS3M"
        - ADMIN_UID= "95374546"